export { default as PracticeAreasMain } from './practice-areas-main'
export { default as PracticeAreasHeader } from './practice-areas-header'
export { default as PracticeAreasCards } from './practice-areas-cards'
export { default as SpecialtyHero } from './specialty-hero'
export { default as SpecialtyContent } from './specialty-content'
export { default as SpecialtyCTA } from './specialty-cta'
export { default as SpecialtySidebar } from './specialty-sidebar'
export { default as SpecialtySlidingSidebar } from './specialty-sliding-sidebar'
